name: osud_final
description: Aplicación de transporte privado con seguimiento GPS.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
# Dependencias de Firebase
  firebase_core: ^1.8.0
  firebase_auth: ^3.1.4
  firebase_database: ^8.0.1
# Dependencia de Google maps
  google_maps_flutter: ^2.1.1
# Dependencia para validar la conectividad 
  connectivity: ^3.0.6
# Dependencia style IOS
  cupertino_icons: ^1.0.2
# Dependencia del localizador
  geolocator: ^8.0.0
# Dependencia para la formulación de peticiones
  http: ^0.13.4
# Dependencia del gestor de estados
  provider: ^6.0.1
#  Dependencia para decodificar y mostar la linea en el mapa
  flutter_polyline_points: ^1.0.0
#  Dependencia de animación de texto
  animated_text_kit: ^4.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Recursos estaticos de la aplicación
  assets:
    - images/

  # Fuente de letras usada en la aplicación
  fonts:
    - family: Brand-Bold
      fonts:
        - asset: fonts/bolt-semibold.ttf
          
    - family: Brand-Regular
      fonts:
        - asset: fonts/bolt-regular.ttf
          

